# Generated by Django 5.1 on 2024-10-25 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_shop', '0002_review_delete_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
    ]
