# Generated by Django 5.1 on 2024-11-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_shop', '0002_remove_user_email_address_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product'),
        ),
    ]
