# Generated by Django 5.1 on 2024-11-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clothes_shop", "0003_cartitem_unique_user_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
