# Generated by Django 5.1 on 2024-11-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_shop', '0005_alter_user_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
