# Generated by Django 5.1 on 2024-11-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_shop', '0007_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(default='https://e-commerce-webapp-image.s3.ap-northeast-1.amazonaws.com/test/no_image_square.jpg'),
        ),
    ]
