# Generated by Django 5.1 on 2024-11-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes_shop', '0008_product_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
