name: CI - Automated Tests

on:
  push:
    branches:
      - develop
      - test-cicd-workflow
  pull_request:
    branches:
      - develop
      - test-cicd-workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Create required directories
      run: |
        mkdir -p src/logs/critical
        mkdir -p src/logs/error
        mkdir -p src/logs/warning
        mkdir -p src/logs/info
        mkdir -p src/logs/debug
        sudo chown -R $USER:$USER src/logs
        chmod -R 777 src/logs

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        echo "LOGGING_DIR=src/logs" >> .env
        echo "CI=true" >> .env
        cp .env src/.env
        cp .env mysql-variables.env

    - name: Build and start services
      run: docker-compose up -d
    
    - name: Check MySQL logs
      run: docker-compose logs db

    - name: Check MySQL readiness
      run: |
        echo "Checking if MySQL is ready for connections..."
        while ! docker-compose exec -T db mysqladmin ping -h"db" --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done
        echo "MySQL is ready!"

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Grant MySQL privileges for app_user
    #   run: |
    #     source .env &&
    #     docker-compose exec -T -e MYSQL_PWD="$MYSQL_ROOT_PASSWORD" db sh -c "
    #       mysql -u root -e '
    #         GRANT ALL PRIVILEGES ON *.* TO '\''$MYSQL_APP_USER'\''@'\''%'\''; 
    #         FLUSH PRIVILEGES;'
    #     "

    # - name: Run Django tests inside Docker
    #   run: |
    #     source .env &&
    #     docker-compose exec -T -e MYSQL_PWD="$MYSQL_APP_USER_PASSWORD" web bash -c "
    #       source /django/venv/bin/activate && python3 manage.py test
    #     "
    - name: Grant MySQL privileges for app_user
      run: |
        docker-compose exec -T db sh -c "
          MYSQL_PWD='${{ secrets.MYSQL_ROOT_PASSWORD }}' mysql -u root -e '
            GRANT ALL PRIVILEGES ON *.* TO '\''${{ secrets.MYSQL_APP_USER }}'\''@'\''%'\''; 
            FLUSH PRIVILEGES;'
        "

    - name: Run Django tests inside Docker
      run: |
        docker-compose exec -T web bash -c "
          source /django/venv/bin/activate &&
          MYSQL_PWD='${{ secrets.MYSQL_APP_USER_PASSWORD }}' python3 manage.py test
        "