name: CI - Automated Tests

on:
  push:
    branches:
      - develop
      - test-cicd-workflow
  pull_request:
    branches:
      - develop
      - test-cicd-workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Create required directories
      run: |
        mkdir -p src/logs/critical
        mkdir -p src/logs/error
        mkdir -p src/logs/warning
        mkdir -p src/logs/info
        mkdir -p src/logs/debug

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        echo "LOGGING_DIR=src/logs" >> .env
        cp .env src/.env
        cp .env mysql-variables.env

    - name: Build and start services
      run: docker-compose up -d

    - name: Wait for MySQL
      run: |
        echo "Waiting for MySQL to be ready..."
        until docker-compose exec -T db mysqladmin ping -h"db" --silent; do
          echo "Waiting for database connection..."
          sleep 5
        done

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django tests
      run: |
        cd src
        . ../venv/bin/activate
        python manage.py test
