name: CI - Automated Tests

on:
  push:
    branches:
      - develop
      - test-cicd-workflow
  pull_request:
    branches:
      - develop
      - test-cicd-workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Create required directories
      run: |
        mkdir -p src/logs/critical
        mkdir -p src/logs/error
        mkdir -p src/logs/warning
        mkdir -p src/logs/info
        mkdir -p src/logs/debug
        sudo chown -R $USER:$USER src/logs
        chmod -R 777 src/logs

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE_CONTENT }}" > .env
        echo "LOGGING_DIR=src/logs" >> .env
        echo "CI=true" >> .env
        cp .env src/.env
        cp .env mysql-variables.env

    - name: Build and start services
      run: docker-compose up -d
    
    - name: Check MySQL logs
      run: docker-compose logs db

    - name: Check MySQL readiness
      run: |
        echo "Checking if MySQL is ready for connections..."
        while ! docker-compose exec -T db mysqladmin ping -h"db" --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 5
        done
        echo "MySQL is ready!"

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
    
    # - name: Reload .env file
    #   run: |
    #     if [ -f .env ]; then
    #       echo "Reloading .env file..."
    #       while IFS= read -r line; do
    #         if [[ "$line" != \#* && "$line" != "" ]]; then
    #           export "$line"
    #           echo "$line" >> $GITHUB_ENV
    #         fi
    #       done < .env
    #     else
    #       echo ".env file not found."
    #       exit 1
    #     fi
    
    - name: Grant MySQL privileges for app_user
      run: |
        docker-compose exec -T db sh -c "
          MYSQL_PWD='${{ secrets.MYSQL_ROOT_PASSWORD }}' mysql -u root -e '
            DROP USER IF EXISTS '\''${{ secrets.MYSQL_APP_USER }}'\''@'\''%'\''; 
            CREATE USER '\''${{ secrets.MYSQL_APP_USER }}'\''@'\''%'\'' IDENTIFIED BY '\''${{ secrets.MYSQL_APP_USER_PASSWORD }}'\''; 
            GRANT ALL PRIVILEGES ON *.* TO '\''${{ secrets.MYSQL_APP_USER }}'\''@'\''%'\''; 
            FLUSH PRIVILEGES;'
        "
      
    - name: Verify MySQL connection from web container
      run: |
        docker-compose exec -T web bash -c "
          MYSQL_PWD='${{ secrets.MYSQL_APP_USER_PASSWORD }}' mysql -u '${{ secrets.MYSQL_APP_USER }}' -h db -e 'SELECT 1;'"
    
    - name: Verify Django DATABASES settings
      run: |
        docker-compose exec -T web bash -c "
          source /django/venv/bin/activate &&
          python3 manage.py shell -c 'from django.conf import settings; print(settings.DATABASES)'"


    - name: Run Django tests inside Docker
      run: |
        source .env &&
        docker-compose exec -T -e MYSQL_PWD="$MYSQL_APP_USER_PASSWORD" web bash -c "
          source /django/venv/bin/activate && python3 manage.py test
        "
