name: CI - Automated Tests

on:
  push:
    branches:
      - develop
      - test-cicd-workflow # 追加: 検証用ブランチでのトリガー
  pull_request:
    branches:
      - develop
      - test-cicd-workflow # 追加: 検証用ブランチのPRも対象

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip install -r src/requirements.txt

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE_CONTENT }}" > src/.env

    - name: Run Django tests
      run: |
        cd src
        . ../venv/bin/activate
        python manage.py test
